# Generated by Django 5.0.14 on 2025-07-09 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syncdata', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='syncedrecord',
            name='ad_enabled',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
