# Generated by Django 5.0.14 on 2025-07-09 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syncdata', '0002_syncedrecord_ad_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='syncedrecord',
            name='distinguished_name',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
